name: Deploy Server Assets to Aliyun OSS

on:
  push:
    branches:
      - main
    paths:
      - 'server-assets/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OSSUTIL
        uses: manyuanrong/setup-oss@v2.0.0
        with:
          key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          bucket: ${{ secrets.OSS_BUCKET }}
          endpoint: ${{ secrets.OSS_ENDPOINT }}

      - name: Upload Server Assets to Aliyun OSS
        run: ossutil cp -r server-assets/ oss://${{ secrets.OSS_BUCKET }}/heyclaw/server-assets/

